### ISSUE TITLE
negative keyrates

### ISSUE THREAD

**Issue by QJaxy** [peterjbrown519/im_divergences#1]
I was trying to run the program, however, instead of positive key rates I am getting negative key rates even for eta = 0.99. I tried for alpha_k = 4/3 as well as alpha_k = 2. For the latter I get some positive key rate but not equal to the one mentioned in the paper (fig 5). 

For eta = 0.99 I am getting keyrate of -0.31 and for eta  = 0.94 I am getting keyrate of -2.35. Could you kindly look into the matter. 

(I am running all the packages with Mosek solver)

**Comment by peterjbrown519** [comment]
Do you have the latest version of ncpol2sdpa installed? You can install it via

pip3 install git+https://github.com/peterjbrown519/ncpol2sdpa

**Comment by QJaxy** [comment]
> Do you have the latest version of ncpol2sdpa installed? You can install it via
> 
> pip3 install git+https://github.com/peterjbrown519/im_divergences.git

Yes I have the latest version (ver 1.12.2).

**Comment by peterjbrown519** [comment]
Did you install it via the method above or via `pip install ncpol2sdpa`?  (The version on Pypi is not up to date.)

**Comment by QJaxy** [comment]
I installed it via pip

**Comment by peterjbrown519** [comment]
Please try running the following commands and then rerun your scripts
```
pip uninstall ncpol2sdpa
pip install git+https://github.com/peterjbrown519/ncpol2sdpa
```

**Comment by QJaxy** [comment]
Thank you for your response. This worked great. However, I have another naive question: I see that the number of iterations has gone down. Does this affect the accuracy? Would it help if I increased the LEVEL to 3?

(I am still learning and your article with examples has proven to be quite helpful. Thank you for that too.)

**Comment by peterjbrown519** [comment]
> I see that the number of iterations has gone down.

Are you referring to the iterations of the solver? This should not affect accuracy, this is just the number of steps that the solver has taken in its internal algorithm when finding the solution. You can look into the various solver errors to check the overall accuracy of the SDP (finite precision computing will always lead to some errors in the constraints). 

> Would it help if I increased the LEVEL to 3?

The computations performed should always lead to lower bounds on the conditional entropy. Increasing the relaxation level **may** lead to better lower bounds but it can be very expensive computationally.

**Comment by QJaxy** [comment]
Thank you.

**Comment by Jorawar-Singh** [comment]
I'm running the code `h43_qkd_example.py` as is, with the only change of `test_eta=0.92`
ncpol2sdpa version 1.12.3
python version 3.9.7
qutip version 4.6.2
mosek version 9.3.7
numpy version 1.21.2
sympy version 1.9

I get the following output:
`For detection efficiency 0.92 the system [0.7853981633974483, 0.0, 1.5707963267948966, 0.7853981633974483, 0.7853981633974483, 0.0] achieves a DI-QKD rate of -0.026621775141335097`

What could be the issue here?
(The rate should be around 0.18 as seen from the graph in the paper)

**Comment by peterjbrown519** [comment]
You are using the maximally entangled state and measurement angles that are optimized for a detection efficiency of 1.0. The optimal system will change as the detection efficiency decreases.

**Comment by phyolization** [comment]
> You are using the maximally entangled state and measurement angles that are optimized for a detection efficiency of 1.0. The optimal system will change as the detection efficiency decreases.

Very helpful!
